# Generated by Django 3.2.3 on 2023-07-28 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20230727_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(help_text='Рецепты, добавленные в избранное', related_name='favorite_recipes', through='recipes.Favorites', to=settings.AUTH_USER_MODEL, verbose_name='Избранные рецепты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='shopping_list_entries',
            field=models.ManyToManyField(help_text='Рецепты, добавленные в список покупок', related_name='shopping_list_recipes', through='recipes.ShoppingList', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок'),
        ),
    ]
